/** 10 vendeurs catalogue — aligné docs/SPEC_VENDEURS_CATALOGUE_CLIENT.txt */
const PASSWORD = 'Vendeur2026!';

const VENDORS = [
  {
    code: 'V01',
    slug: 'techstore-pro',
    email: 'vendeur.techstore-pro@heligxiam.com',
    prenom: 'Marc',
    nom: 'Dupont',
    displayName: 'TechStore Pro',
    raisonSociale: 'TechStore Pro SAS',
    siret: '12345678900011',
    logoFile: 'V01-techstore-pro.svg',
    phone: '+33601000001'
  },
  {
    code: 'V02',
    slug: 'electromarket',
    email: 'vendeur.electromarket@heligxiam.com',
    prenom: 'Sophie',
    nom: 'Martin',
    displayName: 'ElectroMarket',
    raisonSociale: 'ElectroMarket SARL',
    siret: '12345678900012',
    logoFile: 'V02-electromarket.svg',
    phone: '+33601000002'
  },
  {
    code: 'V03',
    slug: 'fashion-hub',
    email: 'vendeur.fashion-hub@heligxiam.com',
    prenom: 'Léa',
    nom: 'Bernard',
    displayName: 'Fashion Hub',
    raisonSociale: 'Fashion Hub SARL',
    siret: '12345678900013',
    logoFile: 'V03-fashion-hub.svg',
    phone: '+33601000003'
  },
  {
    code: 'V04',
    slug: 'nike-flagship',
    email: 'vendeur.nike-flagship@heligxiam.com',
    prenom: 'Thomas',
    nom: 'Petit',
    displayName: 'Nike Flagship',
    raisonSociale: 'Nike Flagship France SAS',
    siret: '12345678900014',
    logoFile: 'V04-nike-flagship.svg',
    phone: '+33601000004'
  },
  {
    code: 'V05',
    slug: 'heligxiam-official',
    email: 'vendeur.heligxiam-official@heligxiam.com',
    prenom: 'Helig',
    nom: 'Xiam',
    displayName: 'HELIGXIAM Official',
    raisonSociale: 'HELIGXIAM SAS',
    siret: '12345678900015',
    logoFile: 'V05-heligxiam-official.svg',
    phone: '+33601000005'
  },
  {
    code: 'V06',
    slug: 'home-essentials',
    email: 'vendeur.home-essentials@heligxiam.com',
    prenom: 'Claire',
    nom: 'Moreau',
    displayName: 'Home Essentials',
    raisonSociale: 'Home Essentials SARL',
    siret: '12345678900016',
    logoFile: 'V06-home-essentials.svg',
    phone: '+33601000006'
  },
  {
    code: 'V07',
    slug: 'beaute-paris-select',
    email: 'vendeur.beaute-paris-select@heligxiam.com',
    prenom: 'Camille',
    nom: 'Roux',
    displayName: 'Beauté Paris Select',
    raisonSociale: 'Beauté Paris Select SARL',
    siret: '12345678900017',
    logoFile: 'V07-beaute-paris-select.svg',
    phone: '+33601000007'
  },
  {
    code: 'V08',
    slug: 'sport-performance',
    email: 'vendeur.sport-performance@heligxiam.com',
    prenom: 'Julien',
    nom: 'Garcia',
    displayName: 'Sport Performance',
    raisonSociale: 'Sport Performance SAS',
    siret: '12345678900018',
    logoFile: 'V08-sport-performance.svg',
    phone: '+33601000008'
  },
  {
    code: 'V09',
    slug: 'auto-expert-france',
    email: 'vendeur.auto-expert-france@heligxiam.com',
    prenom: 'Nicolas',
    nom: 'Lambert',
    displayName: 'Auto Expert France',
    raisonSociale: 'Auto Expert France SARL',
    siret: '12345678900019',
    logoFile: 'V09-auto-expert-france.svg',
    phone: '+33601000009'
  },
  {
    code: 'V10',
    slug: 'samsung-premium',
    email: 'vendeur.samsung-premium@heligxiam.com',
    prenom: 'Min',
    nom: 'Lee',
    displayName: 'Samsung Premium',
    raisonSociale: 'Samsung Premium France SAS',
    siret: '12345678900020',
    logoFile: 'V10-samsung-premium.svg',
    phone: '+33601000010'
  }
];

/** SKU → vendor code V01…V10 — section 4 spec */
const PRODUCTS = [
  { sku: 'P001', vendor: 'V01', title: 'MacBook Pro 16" M3 Max', price: 2899.0, stock: 15, category: 'Électronique' },
  { sku: 'P002', vendor: 'V01', title: 'AirPods Max Silver Edition', price: 579.0, stock: 40, category: 'Électronique' },
  { sku: 'P003', vendor: 'V01', title: 'iPhone 15 Pro Max Titane', price: 1479.0, stock: 25, category: 'Électronique' },
  { sku: 'P004', vendor: 'V01', title: 'iPad Pro 12.9" M2', price: 1449.0, stock: 18, category: 'Électronique' },
  { sku: 'P005', vendor: 'V01', title: 'Casque Audio Aurora', price: 159.0, stock: 80, category: 'Électronique' },
  { sku: 'P006', vendor: 'V01', title: 'Montre connectée Pulse X2', price: 189.0, stock: 50, category: 'Électronique' },
  { sku: 'P007', vendor: 'V01', title: 'AirPods Pro 2 USB-C', price: 189.0, stock: 120, category: 'Électronique', flash: true },
  { sku: 'P008', vendor: 'V01', title: 'iPad Air M2', price: 799.0, stock: 30, category: 'Électronique' },
  { sku: 'P009', vendor: 'V01', title: 'Sony A7R V Full Frame', price: 3899.0, stock: 8, category: 'Électronique' },
  { sku: 'P010', vendor: 'V01', title: 'PlayStation 5 Pro Digital', price: 699.0, stock: 0, category: 'Électronique' },
  { sku: 'P011', vendor: 'V01', title: 'Bose SoundLink Revolve+ II', price: 329.0, stock: 35, category: 'Électronique' },
  { sku: 'P012', vendor: 'V01', title: 'Sony WH-1000XM5', price: 349.0, stock: 0, category: 'Électronique' },
  { sku: 'P013', vendor: 'V02', title: 'Chargeur sans fil 15W', price: 29.9, stock: 200, category: 'Électronique' },
  { sku: 'P014', vendor: 'V02', title: 'Câble USB-C tressé 2m', price: 14.9, stock: 500, category: 'Électronique' },
  { sku: 'P015', vendor: 'V02', title: 'Enceinte Bluetooth Waveform', price: 89.0, stock: 60, category: 'Électronique' },
  { sku: 'P016', vendor: 'V02', title: 'Clavier mécanique RGB', price: 129.9, stock: 45, category: 'Électronique' },
  { sku: 'P017', vendor: 'V02', title: 'Webcam 4K StreamPro', price: 149.0, stock: 30, category: 'Électronique' },
  { sku: 'P018', vendor: 'V10', title: 'Galaxy S24 Ultra 256Go', price: 1199.0, stock: 20, category: 'Électronique' },
  { sku: 'P019', vendor: 'V10', title: 'TV Samsung QLED 55"', price: 899.0, stock: 12, category: 'Électronique' },
  { sku: 'P020', vendor: 'V10', title: 'Écouteurs Samsung Galaxy Buds3', price: 149.0, stock: 80, category: 'Électronique' },
  { sku: 'P021', vendor: 'V01', title: 'Apple Watch Ultra 2 Titanium', price: 899.0, stock: 22, category: 'Mode' },
  { sku: 'P022', vendor: 'V05', title: 'Sac Hermès Kelly Replica Premium', price: 349.0, stock: 40, category: 'Mode' },
  { sku: 'P023', vendor: 'V04', title: 'Sneakers Nike Air Jordan 1 Retro', price: 189.0, stock: 55, category: 'Mode' },
  { sku: 'P024', vendor: 'V03', title: 'Lunettes Ray-Ban Aviator Gold', price: 179.0, stock: 70, category: 'Mode' },
  { sku: 'P025', vendor: 'V05', title: 'Tenue Élégante Mode Luxe', price: 599.0, stock: 15, category: 'Mode' },
  { sku: 'P026', vendor: 'V03', title: 'Sac à dos minimaliste', price: 49.9, stock: 100, category: 'Mode' },
  { sku: 'P027', vendor: 'V03', title: 'T-shirt premium coton bio', price: 39.6, stock: 150, category: 'Mode' },
  { sku: 'P028', vendor: 'V01', title: 'MacBook Air M2', price: 999.99, stock: 10, category: 'Électronique' },
  { sku: 'P029', vendor: 'V04', title: 'Nike Air Max 2026', price: 129.0, stock: 200, category: 'Sport', flash: true },
  { sku: 'P030', vendor: 'V05', title: 'Vase Design Minimaliste', price: 89.0, stock: 80, category: 'Maison' },
  { sku: 'P031', vendor: 'V06', title: 'Machine à Café DeLonghi Dinamica', price: 699.0, stock: 25, category: 'Maison' },
  { sku: 'P032', vendor: 'V06', title: 'Cafetière Delonghi Auto', price: 349.0, stock: 80, category: 'Maison', flash: true },
  { sku: 'P033', vendor: 'V06', title: 'Robot aspirateur iLife Pro', price: 229.0, stock: 150, category: 'Maison', flash: true },
  { sku: 'P034', vendor: 'V06', title: 'Diffuseur huiles essentielles', price: 49.9, stock: 90, category: 'Maison' },
  { sku: 'P035', vendor: 'V06', title: 'Aspirateur Dyson V15 Detect', price: 649.0, stock: 18, category: 'Maison' },
  { sku: 'P036', vendor: 'V07', title: 'Parfum Tom Ford Black Orchid', price: 159.0, stock: 45, category: 'Beauté' },
  { sku: 'P037', vendor: 'V07', title: 'Parfum Coffret premium', price: 79.0, stock: 400, category: 'Beauté', flash: true },
  { sku: 'P038', vendor: 'V07', title: 'Coffret Sephora Best Sellers', price: 59.0, stock: 120, category: 'Beauté' },
  { sku: 'P039', vendor: 'V07', title: "Crème Immortelle L'Occitane 50ml", price: 45.0, stock: 200, category: 'Beauté' },
  { sku: 'P040', vendor: 'V08', title: 'Montre Garmin Fenix 8', price: 699.0, stock: 60, category: 'Sport', flash: true },
  { sku: 'P041', vendor: 'V08', title: 'Chaussures running Adidas Ultraboost', price: 159.0, stock: 85, category: 'Sport' },
  { sku: 'P042', vendor: 'V08', title: 'Haltères réglables 20 kg', price: 129.0, stock: 40, category: 'Sport' },
  { sku: 'P043', vendor: 'V08', title: 'Tapis yoga premium 6mm', price: 39.9, stock: 200, category: 'Sport' },
  { sku: 'P044', vendor: 'V09', title: 'Kit entretien hiver liquide lave-glace', price: 24.9, stock: 300, category: 'Automobile' },
  { sku: 'P045', vendor: 'V09', title: 'Balai essuie-glace Bosch Aerotwin', price: 34.9, stock: 150, category: 'Automobile' },
  { sku: 'P046', vendor: 'V09', title: 'Dashcam Garmin Mini 3', price: 129.0, stock: 45, category: 'Automobile' },
  { sku: 'P047', vendor: 'V09', title: 'Compresseur portable 12V', price: 59.0, stock: 60, category: 'Automobile' }
];

module.exports = { PASSWORD, VENDORS, PRODUCTS };
